# Superuser Permisions
sudo: required
# We need a copy of docker
services: 
  - docker
# Build the image
before_install:
  - docker build -t kostaschikis/docker-react -f Dockerfile.dev .  
# Scripts (-- --coverage->exit the test with exit code)
script: 
 - docker run -e CI=true kostaschikis/docker-react npm run test 
# Deployment
deploy: 
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-832045539600"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"